# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeff/Git/CompressedStacks.cpp/sources

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeff/Git/CompressedStacks.cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeff/Git/CompressedStacks.cpp/CMakeFiles /home/jeff/Git/CompressedStacks.cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeff/Git/CompressedStacks.cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named smartstack

# Build rule for target.
smartstack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smartstack
.PHONY : smartstack

# fast build rule for target.
smartstack/fast:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/build
.PHONY : smartstack/fast

compressedStack.o: compressedStack.cpp.o

.PHONY : compressedStack.o

# target to build an object file
compressedStack.cpp.o:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/compressedStack.cpp.o
.PHONY : compressedStack.cpp.o

compressedStack.i: compressedStack.cpp.i

.PHONY : compressedStack.i

# target to preprocess a source file
compressedStack.cpp.i:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/compressedStack.cpp.i
.PHONY : compressedStack.cpp.i

compressedStack.s: compressedStack.cpp.s

.PHONY : compressedStack.s

# target to generate assembly for a file
compressedStack.cpp.s:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/compressedStack.cpp.s
.PHONY : compressedStack.cpp.s

data.o: data.cpp.o

.PHONY : data.o

# target to build an object file
data.cpp.o:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/data.cpp.o
.PHONY : data.cpp.o

data.i: data.cpp.i

.PHONY : data.i

# target to preprocess a source file
data.cpp.i:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/data.cpp.i
.PHONY : data.cpp.i

data.s: data.cpp.s

.PHONY : data.s

# target to generate assembly for a file
data.cpp.s:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/data.cpp.s
.PHONY : data.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/main.cpp.s
.PHONY : main.cpp.s

normalStack.o: normalStack.cpp.o

.PHONY : normalStack.o

# target to build an object file
normalStack.cpp.o:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/normalStack.cpp.o
.PHONY : normalStack.cpp.o

normalStack.i: normalStack.cpp.i

.PHONY : normalStack.i

# target to preprocess a source file
normalStack.cpp.i:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/normalStack.cpp.i
.PHONY : normalStack.cpp.i

normalStack.s: normalStack.cpp.s

.PHONY : normalStack.s

# target to generate assembly for a file
normalStack.cpp.s:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/normalStack.cpp.s
.PHONY : normalStack.cpp.s

problem.o: problem.cpp.o

.PHONY : problem.o

# target to build an object file
problem.cpp.o:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/problem.cpp.o
.PHONY : problem.cpp.o

problem.i: problem.cpp.i

.PHONY : problem.i

# target to preprocess a source file
problem.cpp.i:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/problem.cpp.i
.PHONY : problem.cpp.i

problem.s: problem.cpp.s

.PHONY : problem.s

# target to generate assembly for a file
problem.cpp.s:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/problem.cpp.s
.PHONY : problem.cpp.s

sign.o: sign.cpp.o

.PHONY : sign.o

# target to build an object file
sign.cpp.o:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/sign.cpp.o
.PHONY : sign.cpp.o

sign.i: sign.cpp.i

.PHONY : sign.i

# target to preprocess a source file
sign.cpp.i:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/sign.cpp.i
.PHONY : sign.cpp.i

sign.s: sign.cpp.s

.PHONY : sign.s

# target to generate assembly for a file
sign.cpp.s:
	$(MAKE) -f CMakeFiles/smartstack.dir/build.make CMakeFiles/smartstack.dir/sign.cpp.s
.PHONY : sign.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... smartstack"
	@echo "... compressedStack.o"
	@echo "... compressedStack.i"
	@echo "... compressedStack.s"
	@echo "... data.o"
	@echo "... data.i"
	@echo "... data.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... normalStack.o"
	@echo "... normalStack.i"
	@echo "... normalStack.s"
	@echo "... problem.o"
	@echo "... problem.i"
	@echo "... problem.s"
	@echo "... sign.o"
	@echo "... sign.i"
	@echo "... sign.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

